server:
  port: ${PORT:8018}
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: customer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

customerservice:
  exchange: customerCreatedExchange
  queue: customerCreatedQueue
  routingkey: customer.created
  userqueue: userCreatedQueueCustomerService

security:
  enabled: false