server:
   port: ${PORT:9080}
application:
   name: ^project.artifactId^
   description: ^project.name^
   version: ^project.version^
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: loan-application-service
        uri: http://localhost:8019/
        predicates:
        - Path=/api/loanapplications**
      - id: customer-service
        uri: http://localhost:8018/
        predicates:
        - Path=/api/customers/**
 
      